### ISSUE TITLE
Ads not showing on ios

### ISSUE THREAD

**Issue by velgajski1** [lilili87222/Unity-ANE#4]
Hi, I'm having an issue where ads sometimes do not show on ios. They are fetched/ready, but when I call showVideo() nothing happens, no ads are displayed. Sometimes it works. Any ideas what the problem might be?

**Comment by lilili87222** [comment]
fixed

**Comment by xietianze** [comment]
seems the bug still exists, sometimes just no video showing.

**Comment by lilili87222** [comment]
Maybe load ads fail.you would better show ad when success event.

**Comment by xietianze** [comment]
thanks, video shown, but video timer stuck when update to ios10, the game crashed.
